# Generated by Django 2.1.1 on 2018-10-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirtle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CP', models.IntegerField()),
                ('HP', models.IntegerField()),
                ('SEX', models.BooleanField()),
                ('WEIGHT', models.FloatField()),
                ('HEIGHT', models.FloatField()),
                ('MOVE1', models.CharField(max_length=10)),
                ('MOVE2', models.CharField(max_length=10)),
            ],
        ),
    ]
