# Generated by Django 2.1.1 on 2018-10-12 03:04

from django.db import migrations, models
import django.db.models.deletion
import hello.models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20181005_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('contemt', models.CharField(max_length=300)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('pub_date',),
            },
        ),
        migrations.AlterField(
            model_name='friend',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='friend',
            name='name',
            field=models.CharField(max_length=100, validators=[hello.models.number_only]),
        ),
        migrations.AddField(
            model_name='message',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Friend'),
        ),
    ]
